### ISSUE TITLE
OSC Drops rapid sequences of cues

### ISSUE THREAD

**Issue by jburkeucla** [remap/LastDays#67] opened 2020-11-29 19:32 UTC
OSC handling drops cues received in rapid succession. Need to implement a queue.

**Comment by peetonn** [comment] 2021-01-06 20:36
The issue is now fixed. Cues were not re-entrant. Implemented re-entrance logic which can be enabled on cue actors by checking "General Purpose Cue".

**Closed as completed by peetonn** 2021-01-06 20:36 UTC
Labels: bug
